resources:
- name: concourse-gitops-examples
  type: git
  icon: github
  source:
    uri: https://github.com/penglei/examples.git


jobs:

- name: configure-self
  plan:
  - get: concourse-gitops-examples
    trigger: true
  - set_pipeline: self
    file: concourse-gitops-examples/pipelines/reconfigure-pipelines.yml

- name: configure-pipelines
  public: true
  plan:
    - get: concourse-gitops-examples
      trigger: true
      passed: [configure-self]
    - set_pipeline: hello-world
      file: concourse-gitops-examples/pipelines/hello-world.yml
#   - set_pipeline: time-triggered
#     file: concourse-gitops-examples/pipelines/time-triggered.yml
